/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiproject;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author user
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    boolean a=true;
    CardLayout cdl;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IconSizeClose = new javax.swing.JPanel();
        max = new javax.swing.JPanel();
        maxClick = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        closeClick = new javax.swing.JLabel();
        min = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        LineAdd = new javax.swing.JPanel();
        Employee = new javax.swing.JPanel();
        ButtonSetting1 = new javax.swing.JLabel();
        LineEmplo = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        ButtonHide = new javax.swing.JLabel();
        LineAdmin = new javax.swing.JPanel();
        Admin = new javax.swing.JPanel();
        ButtonSetting2 = new javax.swing.JLabel();
        Check = new javax.swing.JPanel();
        ButtonSetting3 = new javax.swing.JLabel();
        LineCheck = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        employee = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        admin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(54, 33, 89));
        Header.setPreferredSize(new java.awt.Dimension(450, 50));
        Header.setLayout(new java.awt.BorderLayout());

        IconSizeClose.setBackground(new java.awt.Color(64, 43, 100));
        IconSizeClose.setPreferredSize(new java.awt.Dimension(150, 50));
        IconSizeClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        max.setBackground(new java.awt.Color(54, 33, 89));

        maxClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_expand_32px.png"))); // NOI18N
        maxClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxClickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maxLayout = new javax.swing.GroupLayout(max);
        max.setLayout(maxLayout);
        maxLayout.setHorizontalGroup(
            maxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maxClick, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        maxLayout.setVerticalGroup(
            maxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxLayout.createSequentialGroup()
                .addComponent(maxClick, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        IconSizeClose.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        close.setBackground(new java.awt.Color(54, 33, 89));

        closeClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_shutdown_32px.png"))); // NOI18N
        closeClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeClickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(closeClick, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(closeClick, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        IconSizeClose.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        min.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout minLayout = new javax.swing.GroupLayout(min);
        min.setLayout(minLayout);
        minLayout.setHorizontalGroup(
            minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        minLayout.setVerticalGroup(
            minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        IconSizeClose.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Header.add(IconSizeClose, java.awt.BorderLayout.LINE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("   WORLDWIDE SHIPPING");
        Header.add(jLabel1, java.awt.BorderLayout.CENTER);

        dashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        menuIcon.setBackground(new java.awt.Color(54, 33, 89));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LineAdd.setBackground(new java.awt.Color(54, 33, 89));
        LineAdd.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineAddLayout = new javax.swing.GroupLayout(LineAdd);
        LineAdd.setLayout(LineAddLayout);
        LineAddLayout.setHorizontalGroup(
            LineAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineAddLayout.setVerticalGroup(
            LineAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(LineAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        Employee.setBackground(new java.awt.Color(54, 33, 89));
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeMouseExited(evt);
            }
        });
        Employee.setLayout(new java.awt.BorderLayout());

        ButtonSetting1.setBackground(new java.awt.Color(54, 33, 89));
        ButtonSetting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSetting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_employee_32px.png"))); // NOI18N
        Employee.add(ButtonSetting1, java.awt.BorderLayout.CENTER);

        menuIcon.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        LineEmplo.setBackground(new java.awt.Color(54, 33, 89));
        LineEmplo.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineEmploLayout = new javax.swing.GroupLayout(LineEmplo);
        LineEmplo.setLayout(LineEmploLayout);
        LineEmploLayout.setHorizontalGroup(
            LineEmploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineEmploLayout.setVerticalGroup(
            LineEmploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(LineEmplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        add.setBackground(new java.awt.Color(54, 33, 89));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new java.awt.BorderLayout());

        ButtonHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_add_32px.png"))); // NOI18N
        add.add(ButtonHide, java.awt.BorderLayout.CENTER);

        menuIcon.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        LineAdmin.setBackground(new java.awt.Color(54, 33, 89));
        LineAdmin.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineAdminLayout = new javax.swing.GroupLayout(LineAdmin);
        LineAdmin.setLayout(LineAdminLayout);
        LineAdminLayout.setHorizontalGroup(
            LineAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineAdminLayout.setVerticalGroup(
            LineAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(LineAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 5));

        Admin.setBackground(new java.awt.Color(54, 33, 89));
        Admin.setPreferredSize(new java.awt.Dimension(50, 50));
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
        });
        Admin.setLayout(new java.awt.BorderLayout());

        ButtonSetting2.setBackground(new java.awt.Color(54, 33, 89));
        ButtonSetting2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSetting2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_male_user_32px.png"))); // NOI18N
        Admin.add(ButtonSetting2, java.awt.BorderLayout.CENTER);

        menuIcon.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 50, 50));

        Check.setBackground(new java.awt.Color(54, 33, 89));
        Check.setPreferredSize(new java.awt.Dimension(50, 50));
        Check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckMouseExited(evt);
            }
        });
        Check.setLayout(new java.awt.BorderLayout());

        ButtonSetting3.setBackground(new java.awt.Color(54, 33, 89));
        ButtonSetting3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSetting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiproject/icon/icons8_Check_Circle_32px.png"))); // NOI18N
        Check.add(ButtonSetting3, java.awt.BorderLayout.CENTER);

        menuIcon.add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 50));

        LineCheck.setBackground(new java.awt.Color(54, 33, 89));
        LineCheck.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout LineCheckLayout = new javax.swing.GroupLayout(LineCheck);
        LineCheck.setLayout(LineCheckLayout);
        LineCheckLayout.setHorizontalGroup(
            LineCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LineCheckLayout.setVerticalGroup(
            LineCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(LineCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, 5));

        menu.setFocusable(false);
        menu.setPreferredSize(new java.awt.Dimension(270, 450));
        menu.setLayout(new java.awt.CardLayout());

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout employeeLayout = new javax.swing.GroupLayout(employee);
        employee.setLayout(employeeLayout);
        employeeLayout.setHorizontalGroup(
            employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        employeeLayout.setVerticalGroup(
            employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        menu.add(employee, "Employee");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        menu.add(admin, "Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover,Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1,JPanel h2,JPanel h3,JPanel h4, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(25,29,74));
            h2.setBackground(new Color(54,33,89));
            h3.setBackground(new Color(54,33,89));
            h4.setBackground(new Color(54,33,89));
        }
        else if(numberbool == 2){
            h1.setBackground(new Color(54,33,89));
            h2.setBackground(new Color(25,29,74));
            h3.setBackground(new Color(54,33,89));
            h4.setBackground(new Color(54,33,89));
        }else if(numberbool == 3){
            h1.setBackground(new Color(54,33,89));
            h2.setBackground(new Color(54,33,89));
            h3.setBackground(new Color(25,29,74));
            h4.setBackground(new Color(54,33,89));
        }else {
            h1.setBackground(new Color(54,33,89));
            h2.setBackground(new Color(54,33,89));
            h3.setBackground(new Color(54,33,89));
            h4.setBackground(new Color(25,29,74));
        }
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard,JLabel Button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
        }
        else{
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));}
    }
    
    private void closeClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeClickMouseEntered
        changecolor(close,new Color(85,65,118));
    }//GEN-LAST:event_closeClickMouseEntered

    private void closeClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeClickMouseExited
        changecolor(close,new Color(54,33,89));
    }//GEN-LAST:event_closeClickMouseExited

    private void closeClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeClickMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeClickMouseClicked

    private void maxClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxClickMouseEntered
        changecolor(max,new Color(85,65,118));
    }//GEN-LAST:event_maxClickMouseEntered

    private void maxClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxClickMouseExited
        changecolor(max,new Color(54,33,89));
    }//GEN-LAST:event_maxClickMouseExited

    private void maxClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxClickMouseClicked
        if(this.getExtendedState() != Main.MAXIMIZED_BOTH){
            this.setExtendedState(Main.MAXIMIZED_BOTH);
    }
        else{
            this.setExtendedState(Main.NORMAL);}
    }//GEN-LAST:event_maxClickMouseClicked
    
    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        changecolor(LineAdd,new Color(255,0,0));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        changecolor(LineAdd,new Color(54,33,89));
    }//GEN-LAST:event_addMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        clickmenu(add, Employee,Admin,Check,1);
        //create void for methode hide and show panel menu
        menu.setVisible(false);
    }//GEN-LAST:event_addMouseClicked

    private void EmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseEntered
        changecolor(LineEmplo,new Color(255,0,0));
    }//GEN-LAST:event_EmployeeMouseEntered

    private void EmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseExited
        changecolor(LineEmplo,new Color(54,33,89));
    }//GEN-LAST:event_EmployeeMouseExited

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        clickmenu(add, Employee,Admin,Check,2);
        menu.setVisible(true);
        cdl = (CardLayout)menu.getLayout();
        cdl.show(menu,"Employee");
    }//GEN-LAST:event_EmployeeMouseClicked

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
        clickmenu(add, Employee,Admin,Check,3);
        menu.setVisible(true);
        cdl = (CardLayout)menu.getLayout();
        cdl.show(menu,"Admin");
    }//GEN-LAST:event_AdminMouseClicked

    private void AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseEntered
        changecolor(LineAdmin,new Color(255,0,0));
    }//GEN-LAST:event_AdminMouseEntered

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
        changecolor(LineAdmin,new Color(54,33,89));
    }//GEN-LAST:event_AdminMouseExited

    private void CheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseClicked
        clickmenu(add, Employee,Admin,Check,4);
        menu.setVisible(false);
    }//GEN-LAST:event_CheckMouseClicked

    private void CheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseEntered
        changecolor(LineCheck,new Color(255,0,0));
    }//GEN-LAST:event_CheckMouseEntered

    private void CheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMouseExited
        changecolor(LineCheck,new Color(54,33,89));
    }//GEN-LAST:event_CheckMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JLabel ButtonHide;
    private javax.swing.JLabel ButtonSetting1;
    private javax.swing.JLabel ButtonSetting2;
    private javax.swing.JLabel ButtonSetting3;
    private javax.swing.JPanel Check;
    private javax.swing.JPanel Employee;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel IconSizeClose;
    private javax.swing.JPanel LineAdd;
    private javax.swing.JPanel LineAdmin;
    private javax.swing.JPanel LineCheck;
    private javax.swing.JPanel LineEmplo;
    private javax.swing.JPanel add;
    private javax.swing.JPanel admin;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeClick;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel employee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel max;
    private javax.swing.JLabel maxClick;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel min;
    // End of variables declaration//GEN-END:variables
}
