/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trueproject;

import javax.swing.*;

/**
 *
 * @author user
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form NewOrders
     */
    public Order() {
        initComponents();
        Name.setHint("Your Name");
        Name.setBorder(BorderFactory.createCompoundBorder(
        Name.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        
        Surname.setHint("Your Surname");
        Surname.setBorder(BorderFactory.createCompoundBorder(
        Surname.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        
        Address.setHint("Your Address");
        Address.setBorder(BorderFactory.createCompoundBorder(
        Address.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        
        Type.setHint("Your Parcel Type");
        Type.setBorder(BorderFactory.createCompoundBorder(
        Type.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        
        Box.setHint("Box weight and size");
        Box.setBorder(BorderFactory.createCompoundBorder(
        Box.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address2 = new javax.swing.JTextField();
        Menu = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Head = new javax.swing.JLabel();
        Orders = new javax.swing.JPanel();
        OrderButton = new javax.swing.JLabel();
        Employee = new javax.swing.JPanel();
        EmployeeButton = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        AdminButton = new javax.swing.JLabel();
        Check = new javax.swing.JPanel();
        CheckButton = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        HeadDash = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        normal = new javax.swing.JPanel();
        NormalButton = new javax.swing.JLabel();
        Fast = new javax.swing.JPanel();
        FastButton = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Name = new swing.SearchText();
        Surname = new swing.SearchText();
        Address = new swing.SearchText();
        Type = new swing.SearchText();
        Box = new swing.SearchText();

        Address2.setBackground(new java.awt.Color(204, 204, 204));
        Address2.setText("address");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 446));

        Menu.setBackground(new java.awt.Color(54, 33, 89));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trueproject/image/icons8_shutdown_32px.png"))); // NOI18N

        Head.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Head.setForeground(new java.awt.Color(255, 255, 255));
        Head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Head.setText("WORLDWIDE");

        Orders.setBackground(new java.awt.Color(85, 65, 118));

        OrderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderButton.setText("NEW ORDERS");

        javax.swing.GroupLayout OrdersLayout = new javax.swing.GroupLayout(Orders);
        Orders.setLayout(OrdersLayout);
        OrdersLayout.setHorizontalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OrdersLayout.setVerticalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Employee.setBackground(new java.awt.Color(85, 65, 118));

        EmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeButton.setText("EMPLOYEE");

        javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
        Employee.setLayout(EmployeeLayout);
        EmployeeLayout.setHorizontalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EmployeeLayout.setVerticalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Admin.setBackground(new java.awt.Color(85, 65, 118));

        AdminButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminButton.setForeground(new java.awt.Color(255, 255, 255));
        AdminButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminButton.setText("ADMIN");

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Check.setBackground(new java.awt.Color(85, 65, 118));

        CheckButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckButton.setText("CHECK");

        javax.swing.GroupLayout CheckLayout = new javax.swing.GroupLayout(Check);
        Check.setLayout(CheckLayout);
        CheckLayout.setHorizontalGroup(
            CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CheckLayout.setVerticalGroup(
            CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Exit)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        HeadDash.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HeadDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadDash.setText("ORDER");

        Generate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Generate.setText("Generate");

        NormalButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NormalButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NormalButton.setText("Normal send");

        javax.swing.GroupLayout normalLayout = new javax.swing.GroupLayout(normal);
        normal.setLayout(normalLayout);
        normalLayout.setHorizontalGroup(
            normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NormalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        normalLayout.setVerticalGroup(
            normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NormalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        FastButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FastButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FastButton.setText("Fast send");

        javax.swing.GroupLayout FastLayout = new javax.swing.GroupLayout(Fast);
        Fast.setLayout(FastLayout);
        FastLayout.setHorizontalGroup(
            FastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FastButton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        FastLayout.setVerticalGroup(
            FastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FastButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Name.setMinimumSize(new java.awt.Dimension(35, 20));
        Name.setPreferredSize(new java.awt.Dimension(51, 20));

        Surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Surname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Surname.setMinimumSize(new java.awt.Dimension(35, 20));
        Surname.setPreferredSize(new java.awt.Dimension(51, 20));

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Address.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Address.setMinimumSize(new java.awt.Dimension(35, 20));
        Address.setPreferredSize(new java.awt.Dimension(51, 20));

        Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Type.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Type.setMinimumSize(new java.awt.Dimension(35, 20));
        Type.setPreferredSize(new java.awt.Dimension(51, 20));

        Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Box.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Box.setMinimumSize(new java.awt.Dimension(35, 20));
        Box.setPreferredSize(new java.awt.Dimension(51, 20));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 163, Short.MAX_VALUE)
                            .addComponent(Surname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Box, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Generate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(normal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(HeadDash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(HeadDash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(normal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Generate)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 376, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.SearchText Address;
    private javax.swing.JTextField Address2;
    private javax.swing.JPanel Admin;
    private javax.swing.JLabel AdminButton;
    private swing.SearchText Box;
    private javax.swing.JPanel Check;
    private javax.swing.JLabel CheckButton;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Employee;
    private javax.swing.JLabel EmployeeButton;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Fast;
    private javax.swing.JLabel FastButton;
    private javax.swing.JButton Generate;
    private javax.swing.JLabel Head;
    private javax.swing.JLabel HeadDash;
    private javax.swing.JPanel Menu;
    private swing.SearchText Name;
    private javax.swing.JLabel NormalButton;
    private javax.swing.JLabel OrderButton;
    private javax.swing.JPanel Orders;
    private swing.SearchText Surname;
    private swing.SearchText Type;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel normal;
    // End of variables declaration//GEN-END:variables
}
