/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trueproject;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author user
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form NewOrders
     */
    static String track;

    public Order() {
        initComponents();
        Name.setHint("Your Name");
        Name.setBorder(BorderFactory.createCompoundBorder(Name.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        destination.setHint("Your destination");
        destination.setBorder(BorderFactory.createCompoundBorder(destination.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        Surname.setHint("Your Surname");
        Surname.setBorder(BorderFactory.createCompoundBorder(Surname.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        Address.setHint("Your Address");
        Address.setBorder(BorderFactory.createCompoundBorder(Address.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        Type.setHint("Your Parcel Type");
        Type.setBorder(BorderFactory.createCompoundBorder(Type.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    }

    public static String Random_Track() {
        String track = "", query;
        try {
            ConnectionDB db = new ConnectionDB();
            ResultSet rs;
            Random rd = new Random();
            while (true) {
                for (int i = 0; i <= 6; i++) {
                    track += String.valueOf(rd.nextInt(10));
                }
                query = String.format("SELECT ID_track FROM orders WHERE ID_track= '%s')", track);
                rs = db.get_resultset(query);
                rs.next();
                db.disconnect();
            }
        } catch (Exception e) {
            return track;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Head = new javax.swing.JLabel();
        Orders = new javax.swing.JPanel();
        OrderButton = new javax.swing.JLabel();
        Employee = new javax.swing.JPanel();
        EmployeeButton = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        AdminButton = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        HeadDash = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        Name = new swing.SearchText();
        Surname = new swing.SearchText();
        Address = new swing.SearchText();
        Type = new swing.SearchText();
        destination = new swing.SearchText();
        box = new javax.swing.JComboBox<>();

        Address2.setBackground(new java.awt.Color(204, 204, 204));
        Address2.setText("address");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 446));

        Menu.setBackground(new java.awt.Color(54, 33, 89));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trueproject/image/icons8_shutdown_32px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        Head.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Head.setForeground(new java.awt.Color(255, 255, 255));
        Head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Head.setText("WORLDWIDE");

        Orders.setBackground(new java.awt.Color(85, 65, 118));

        OrderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderButton.setText("NEW ORDERS");
        OrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout OrdersLayout = new javax.swing.GroupLayout(Orders);
        Orders.setLayout(OrdersLayout);
        OrdersLayout.setHorizontalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OrdersLayout.setVerticalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Employee.setBackground(new java.awt.Color(85, 65, 118));

        EmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeButton.setText("EMPLOYEE");
        EmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
        Employee.setLayout(EmployeeLayout);
        EmployeeLayout.setHorizontalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EmployeeLayout.setVerticalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        Admin.setBackground(new java.awt.Color(85, 65, 118));

        AdminButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminButton.setForeground(new java.awt.Color(255, 255, 255));
        AdminButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminButton.setText("ADMIN");
        AdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Exit)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        HeadDash.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HeadDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadDash.setText("ORDER");

        Generate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Generate.setText("Generate");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });

        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Name.setMinimumSize(new java.awt.Dimension(35, 20));
        Name.setPreferredSize(new java.awt.Dimension(51, 20));

        Surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Surname.setMinimumSize(new java.awt.Dimension(35, 20));
        Surname.setPreferredSize(new java.awt.Dimension(51, 20));

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Address.setMinimumSize(new java.awt.Dimension(35, 20));
        Address.setPreferredSize(new java.awt.Dimension(51, 20));

        Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Type.setMinimumSize(new java.awt.Dimension(35, 20));
        Type.setPreferredSize(new java.awt.Dimension(51, 20));

        destination.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOX SIZE", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL" }));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadDash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Surname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(Generate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(HeadDash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Surname, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destination, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(Generate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 526, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        Name.getText();
        Surname.getText();
        Address.getText();
        int box_cost = 0, cost = 0;
        String d = destination.getText();
        String b = box.getSelectedItem().toString();
        String[] bkk = {"Bangkok", "Nakhon Pathom", "Nonthaburi", "Pathum Thani", "Samut Prakan", "Samut Sakhon"};

        switch (b) {
            case "XS":
                box_cost = 8;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 50 + 20 + box_cost;
                    } else {
                        cost = 55 + 20 + box_cost;
                    }
                }
                break;

            case "S":
                box_cost = 10;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 60 + 20 + box_cost;
                    } else {
                        cost = 75 + 20 + box_cost;
                    }
                }
                break;

            case "M":
                box_cost = 15;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 75 + 20 + box_cost;
                    } else {
                        cost = 85 + 20 + box_cost;
                    }
                }
                break;

            case "L":
                box_cost = 20;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 90 + 30 + box_cost;
                    } else {
                        cost = 110 + 30 + box_cost;
                    }
                }
                break;

            case "XL":
                box_cost = 30;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 110 + 35 + box_cost;
                    } else {
                        cost = 130 + 35 + box_cost;
                    }
                }
                break;

            case "2XL":
                box_cost = 40;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 210 + 40 + box_cost;
                    } else {
                        cost = 230 + 40 + box_cost;
                    }
                }
                break;

            case "3XL":
                box_cost = 50;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 270 + 70 + box_cost;
                    } else {
                        cost = 300 + 70 + box_cost;
                    }
                }
                break;

            case "4XL":
                box_cost = 60;
                for (int i = 0; i < bkk.length; i++) {
                    if (bkk[i].equalsIgnoreCase(d)) {
                        cost = 360 + 90 + box_cost;
                    } else {
                        cost = 380 + 90 + box_cost;
                    }
                }
                break;
        }
        String status = "receive parcels";
        track = Random_Track();
        String sql = String.format("INSERT INTO orders VALUES('%s','%s','%s','%s','%s','%s','%d','%s') ", track, Name.getText(), Surname.getText(), Address.getText(), d, Type.getText(), cost, status);
        try {
            ConnectionDB db = new ConnectionDB();
            if (db.execute(sql)) {
                JOptionPane.showMessageDialog(this, "Success");
                this.setVisible(false);
                OR_Detail ord = new OR_Detail();
                ord.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Fail");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fail");

        }
    }//GEN-LAST:event_GenerateActionPerformed

    private void OrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseClicked
        this.dispose();
        Order order = new Order();
        order.setVisible(true);
    }//GEN-LAST:event_OrderButtonMouseClicked

    private void OrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseEntered
        Orders.setBackground(new Color(125, 109, 151));
        Employee.setBackground(new Color(85, 65, 118));
        Admin.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_OrderButtonMouseEntered

    private void OrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButtonMouseExited
        Orders.setBackground(new Color(85, 65, 118));
        Employee.setBackground(new Color(85, 65, 118));
        Admin.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_OrderButtonMouseExited

    private void EmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeButtonMouseClicked
        this.dispose();
        EM_Login lg = new EM_Login();
        lg.setVisible(true);
    }//GEN-LAST:event_EmployeeButtonMouseClicked

    private void EmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeButtonMouseEntered
        Orders.setBackground(new Color(85, 65, 118));
        Employee.setBackground(new Color(125, 109, 151));
        Admin.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_EmployeeButtonMouseEntered

    private void EmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeButtonMouseExited
        Orders.setBackground(new Color(85, 65, 118));
        Employee.setBackground(new Color(85, 65, 118));
        Admin.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_EmployeeButtonMouseExited

    private void AdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseClicked
        this.dispose();
        AM_login lg = new AM_login();
        lg.setVisible(true);
    }//GEN-LAST:event_AdminButtonMouseClicked

    private void AdminButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseEntered
        Orders.setBackground(new Color(85, 65, 118));
        Employee.setBackground(new Color(85, 65, 118));
        Admin.setBackground(new Color(125, 109, 151));
    }//GEN-LAST:event_AdminButtonMouseEntered

    private void AdminButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseExited
        Orders.setBackground(new Color(85, 65, 118));
        Employee.setBackground(new Color(85, 65, 118));
        Admin.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_AdminButtonMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.SearchText Address;
    private javax.swing.JTextField Address2;
    private javax.swing.JPanel Admin;
    private javax.swing.JLabel AdminButton;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Employee;
    private javax.swing.JLabel EmployeeButton;
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Generate;
    private javax.swing.JLabel Head;
    private javax.swing.JLabel HeadDash;
    private javax.swing.JPanel Menu;
    private swing.SearchText Name;
    private javax.swing.JLabel OrderButton;
    private javax.swing.JPanel Orders;
    private swing.SearchText Surname;
    private swing.SearchText Type;
    private javax.swing.JComboBox<String> box;
    private javax.swing.ButtonGroup buttonGroup1;
    private swing.SearchText destination;
    // End of variables declaration//GEN-END:variables
}
